<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <AssemblyName>GroundRoads</AssemblyName>
    <RootNamespace>GroundRoads</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>0.5.0</Version>
    <FileVersion>0.5.0.0</FileVersion>
    <AssemblyVersion>0.5.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Mafi">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mafi.Core">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mafi.Base">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.Base.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mafi.Unity">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.Unity.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MultiLangLib">
      <HintPath>$(APPDATA)\Captain of Industry\Mods\MultiLangLib\MultiLangLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None
      Include="..\lang\**\*.json"
      Link="lang\%(RecursiveDir)%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest" />
    <None
      Include="..\lang\README.md"
      Link="lang\README.md"
      CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target
    Name="DeployReleaseDllToModRoot"
    AfterTargets="Build"
    Condition="'$(Configuration)' == 'Release' and
               '$(DesignTimeBuild)' != 'true'">
    <Copy
      SourceFiles="$(TargetPath)"
      DestinationFiles="$(MSBuildProjectDirectory)\..\GroundRoads.dll" />
  </Target>

</Project>
